-- OTBASY production schema for Supabase
-- Run this file once in Supabase SQL Editor before deploying Vercel.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  role text not null default 'content_manager' check (role in ('admin', 'content_manager')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.settings (
  id integer primary key default 1 check (id = 1),
  "storeName" text default 'ОТБАСЫ',
  eyebrow text default 'Instagram витрина',
  "heroTitle" text default 'Товары для дома и семьи',
  "heroButtonText" text default 'Смотреть товары',
  "catalogTitle" text default 'Популярные товары',
  "searchPlaceholder" text default 'Найти товар из обзора...',
  "kaspiStoreUrl" text default '',
  "kaspiStoreTitle" text default 'Все товары ОТБАСЫ',
  "kaspiStoreSubtitle" text default 'Открыть магазин на Kaspi',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  sort integer not null default 50,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category_id uuid references public.categories(id) on delete set null,
  category text not null default 'Без категории',
  tag text not null default 'none' check (tag in ('none', 'hit', 'new', 'promo')),
  status text not null default 'draft' check (status in ('active', 'draft', 'hidden')),
  image_url text default '',
  images jsonb not null default '[]'::jsonb,
  kaspi_url text default '',
  video_url text default '',
  sort integer not null default 100,
  note text default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('product_view', 'video_click', 'kaspi_click', 'tab_click', 'filter_change', 'gallery_open')),
  product_id uuid references public.products(id) on delete set null,
  session_id text,
  tab text,
  category_filter text,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);


create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role, is_active)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    case when (new.raw_user_meta_data ->> 'role') in ('admin', 'content_manager') then new.raw_user_meta_data ->> 'role' else 'content_manager' end,
    true
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = coalesce(nullif(excluded.full_name, ''), public.profiles.full_name),
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_create_profile on auth.users;
create trigger on_auth_user_created_create_profile
  after insert on auth.users
  for each row execute function public.handle_new_user_profile();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_profiles_updated_at on public.profiles;
create trigger touch_profiles_updated_at before update on public.profiles for each row execute function public.touch_updated_at();

drop trigger if exists touch_settings_updated_at on public.settings;
create trigger touch_settings_updated_at before update on public.settings for each row execute function public.touch_updated_at();

drop trigger if exists touch_categories_updated_at on public.categories;
create trigger touch_categories_updated_at before update on public.categories for each row execute function public.touch_updated_at();

drop trigger if exists touch_products_updated_at on public.products;
create trigger touch_products_updated_at before update on public.products for each row execute function public.touch_updated_at();

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles p
  where p.id = auth.uid()
    and p.is_active = true
  limit 1;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_app_role() = 'admin', false);
$$;

create or replace function public.can_manage_content()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_app_role() in ('admin', 'content_manager'), false);
$$;

alter table public.profiles enable row level security;
alter table public.settings enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.analytics_events enable row level security;

-- Profiles
DROP POLICY IF EXISTS "profiles_select_own_or_admin" ON public.profiles;
CREATE POLICY "profiles_select_own_or_admin" ON public.profiles
  FOR SELECT USING (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS "profiles_update_admin" ON public.profiles;
CREATE POLICY "profiles_update_admin" ON public.profiles
  FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Settings
DROP POLICY IF EXISTS "settings_public_read" ON public.settings;
CREATE POLICY "settings_public_read" ON public.settings
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "settings_admin_write" ON public.settings;
CREATE POLICY "settings_admin_write" ON public.settings
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Categories
DROP POLICY IF EXISTS "categories_public_read_active" ON public.categories;
CREATE POLICY "categories_public_read_active" ON public.categories
  FOR SELECT USING (is_active = true OR public.can_manage_content());

DROP POLICY IF EXISTS "categories_manage_content" ON public.categories;
CREATE POLICY "categories_manage_content" ON public.categories
  FOR ALL USING (public.can_manage_content()) WITH CHECK (public.can_manage_content());

-- Products
DROP POLICY IF EXISTS "products_public_read_active" ON public.products;
CREATE POLICY "products_public_read_active" ON public.products
  FOR SELECT USING (status = 'active' OR public.can_manage_content());

DROP POLICY IF EXISTS "products_manage_content" ON public.products;
CREATE POLICY "products_manage_content" ON public.products
  FOR ALL USING (public.can_manage_content()) WITH CHECK (public.can_manage_content());

-- Analytics
DROP POLICY IF EXISTS "analytics_public_insert" ON public.analytics_events;
CREATE POLICY "analytics_public_insert" ON public.analytics_events
  FOR INSERT WITH CHECK (event_type in ('product_view', 'video_click', 'kaspi_click', 'tab_click', 'filter_change', 'gallery_open'));

DROP POLICY IF EXISTS "analytics_admin_read" ON public.analytics_events;
CREATE POLICY "analytics_admin_read" ON public.analytics_events
  FOR SELECT USING (public.can_manage_content());

DROP POLICY IF EXISTS "analytics_admin_delete" ON public.analytics_events;
CREATE POLICY "analytics_admin_delete" ON public.analytics_events
  FOR DELETE USING (public.is_admin());

-- Storage bucket for product photos. Public read, authenticated content managers/admins can upload.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

DROP POLICY IF EXISTS "product_images_public_read" ON storage.objects;
CREATE POLICY "product_images_public_read" ON storage.objects
  FOR SELECT USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "product_images_upload_content" ON storage.objects;
CREATE POLICY "product_images_upload_content" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'product-images' AND public.can_manage_content());

DROP POLICY IF EXISTS "product_images_update_content" ON storage.objects;
CREATE POLICY "product_images_update_content" ON storage.objects
  FOR UPDATE USING (bucket_id = 'product-images' AND public.can_manage_content()) WITH CHECK (bucket_id = 'product-images' AND public.can_manage_content());

DROP POLICY IF EXISTS "product_images_delete_content" ON storage.objects;
CREATE POLICY "product_images_delete_content" ON storage.objects
  FOR DELETE USING (bucket_id = 'product-images' AND public.can_manage_content());

-- Initial vitrine content. Safe to rerun.
insert into public.settings (id, "storeName", eyebrow, "heroTitle", "heroButtonText", "catalogTitle", "searchPlaceholder", "kaspiStoreTitle", "kaspiStoreSubtitle")
values (1, 'ОТБАСЫ', 'Instagram витрина', 'Товары для дома и семьи', 'Смотреть товары', 'Популярные товары', 'Найти товар из обзора...', 'Все товары ОТБАСЫ', 'Открыть магазин на Kaspi')
on conflict (id) do nothing;

insert into public.categories (name, sort, is_active)
values ('Дом', 10, true), ('Техника', 20, true), ('Съемка', 30, true), ('Уход', 40, true)
on conflict do nothing;

insert into public.products (id, title, category, tag, status, image_url, images, kaspi_url, video_url, sort, note)
values
('11111111-1111-4111-8111-111111111111', 'Умный увлажнитель воздуха', 'Дом', 'hit', 'active', '/assets/product-diffuser.png', '["/assets/product-diffuser.png", "/assets/gallery-diffuser-2.svg", "/assets/gallery-diffuser-3.svg", "/assets/gallery-diffuser-4.svg", "/assets/gallery-diffuser-5.svg"]'::jsonb, '', '', 10, ''),
('22222222-2222-4222-8222-222222222222', 'Мини-блендер для смузи', 'Техника', 'new', 'active', '/assets/product-blender.png', '["/assets/product-blender.png", "/assets/gallery-blender-2.svg", "/assets/gallery-blender-3.svg", "/assets/gallery-blender-4.svg", "/assets/gallery-blender-5.svg"]'::jsonb, '', '', 20, ''),
('33333333-3333-4333-8333-333333333333', 'LED-лампа для съемки', 'Съемка', 'promo', 'active', '/assets/product-light.png', '["/assets/product-light.png", "/assets/gallery-light-2.svg", "/assets/gallery-light-3.svg", "/assets/gallery-light-4.svg", "/assets/gallery-light-5.svg"]'::jsonb, '', '', 30, ''),
('44444444-4444-4444-8444-444444444444', 'Органайзер для косметики', 'Уход', 'new', 'active', '/assets/product-organizer.png', '["/assets/product-organizer.png", "/assets/gallery-organizer-2.svg", "/assets/gallery-organizer-3.svg", "/assets/gallery-organizer-4.svg", "/assets/gallery-organizer-5.svg"]'::jsonb, '', '', 40, '')
on conflict (id) do nothing;

-- After creating your first Auth user in Supabase Dashboard, run this once with your email:
-- update public.profiles set role = 'admin', is_active = true where email = 'YOUR_EMAIL@example.com';
-- If profile does not exist yet, create it with the Auth user's UUID from Dashboard:
-- insert into public.profiles (id, email, full_name, role, is_active) values ('AUTH_USER_UUID', 'YOUR_EMAIL@example.com', 'Owner', 'admin', true)
-- on conflict (id) do update set role = 'admin', is_active = true;
